### ISSUE TITLE
Presume Namespace of Controller

### ISSUE THREAD

**Issue by swt83** [lesichkovm/laravel-advanced-route#10]
In my fork I made this simple change:

https://github.com/swt83/php-laravel-advanced-route/commit/f1b30b648f2eeffe9645b809422f1b7bfedd0f0b#diff-5a05f9e47fcf36d08a3a8edc918384a3

This allows me to use Controllers in my third-party packages instead of assuming they live in the Apps namespace.  If you added this change into your repo and added a new tag (v1.0.1) then I could use your package instead of mine.

**Comment by lesichkovm** [comment]
Excellent add on. Please create a pull request, and I will merge it in.

**Comment by lesichkovm** [comment]
@swt83 Actually, it will break Laravel compatibility. The best is if we add a third argument for additional options.

AdvancedRoute::controller('cms', 'CustomNamespace\MyController', ['namespace'=>'custom']);

**Comment by rigeliux** [comment]
yes yes... I like the idea of 3rd argument, for options, like route names ;)
+1

**Comment by mexcoder** [comment]
+1 for route names, also great if the class can infere the route controller based on the namespace/class name or an optional variable in the class

**Comment by lesichkovm** [comment]
Closing this issue, as implementing this feature breaks the package. The feature can be implemented using the method described here, which will not break compatibility.
@swt83 , @rigeliux, @mexcoder  if anyone would like to implement this new feature request using 3rd argument for additional options, please feel free to do so, and submit a new pull request.
Thank you all for the great work so far.

**Comment by bs-thomas** [comment]
Can you please reopen this, I've created a non-breaking pull request.  Thanks!
