### ISSUE TITLE
Advance Routing is no working.

### ISSUE THREAD

**Issue by imshibaji** [lesichkovm/laravel-advanced-route#13]
I am developing So many routing features with this. Please Fix the bug

**Comment by imshibaji** [comment]
When I reinstall the package in my laravel package. The Problem is fixed.

**Comment by lesichkovm** [comment]
Thanks for reporting it. I was surprised. I am using it on many projects without a glitch. Working like a charm :)

**Comment by imshibaji** [comment]
Thanks for your reply. But solved my problem. 👍  :)
