### ISSUE TITLE
Using AdvancedRoute with a parameter

### ISSUE THREAD

**Issue by dweinerATL** [lesichkovm/laravel-advanced-route#16]
How would I use AdvancedRoute with a url parameter?

Given the following in web.php:

`AdvancedRoute::controller('/upload', 'UploadController');`

And a `getSheet` method in UploadController.php with the signature 

`public function getSheet(string $chapter)`

If I wanted to use a URL like `/upload/sheet/55fa1833e4bed832078b45dc`, what do I need to do in the `AdvancedRoute::controller()` settings?

Right now, I get a 404 File not Found error when I try it.

Thanks!

**Comment by dweinerATL** [comment]
I've done some further troubleshooting, and it seems that if I remove the type hint in the function signature, it works.

Before I go changing this behavior, is there a reason you skip type hinted parameters?

**Comment by Sinevia** [comment]
I personally try to avoid using passing parameters as part of the URL structure.  There is an already defined standard way of doing this and this is a GET parameter (i.e. /upload/sheet?id=55fa1833e4bed832078b45dc)

The only time I can accept using this is for SEO purposes for public URLs (i.e. /article/23/article-title)

Then and only then I would explicitly define the behavior to make it really clear that I deviate from all standards:

 Route::any('/blog/{Title?}/{PostId}', 'Website\BlogController@anyBlogPost');
