### ISSUE TITLE
not working with custom namespace

### ISSUE THREAD

**Issue by szamanr** [lesichkovm/laravel-advanced-route#17]
installing this plugin breaks my app. here's my routes file:
```
Route::group(['prefix' => 'application', 'namespace' => 'Application', 'middleware'=>[
	'csrf', 
	'auth'
]], function() {
	// home controller
	Route::get('customers', ['as'=>'customers', 'uses'=>'HomeController@getCustomers']);
	
	AdvancedRoute::controllers([
		'user' => 'UserController',
		'system' => 'SystemController',
		'media' => 'MediaController',
                'instructions' => 'InstructionsController',
		'session' => 'SessionController',
	]);
});
```

when i try to launch the app, i'm getting:
`[ReflectionException]
  Class App\Http\Controllers\UserController does not exist`

my UserController is in `app/Http/Controllers/Application/UserController.php`, as indicated in the namespace parameter.

**Comment by lesichkovm** [comment]
You will have to set the fully qualified namespace, not just UserController
