### ISSUE TITLE
Controller::missingMethod() not working

### ISSUE THREAD

**Issue by puggan** [lesichkovm/laravel-advanced-route#19]
Controllers that used missingMethod() is not working

**Comment by Sinevia** [comment]
I believe you already sorted this out. Thank you. It has now been pushed live as new release, and can be used from within composer.

**Comment by puggan** [comment]
:-) Yhea, that how open source works, 1. find a problem, 2. report it, 3. try to solve it yourself, 4. push it upstreams / make a pull request
