### ISSUE TITLE
Wildcard not added

### ISSUE THREAD

**Issue by puggan** [lesichkovm/laravel-advanced-route#21]
The old function added wildcards to the url
"/path/{one?}/{two?}/{three?}/{four?}/{five?}".

**Comment by Sinevia** [comment]
I cannot implement this myself. But will be happy to merge if someone can implement this feature.

**Comment by puggan** [comment]
I may try it later, I solved it by using the emitter, and then manualy add the wildcards to the routes.

**Comment by sam-fls** [comment]
Please suggest the method for the same. I have to implement

**Comment by puggan** [comment]
@sam-fls 

1. Turn on the emmiter:
https://github.com/lesichkovm/laravel-advanced-route/blob/master/src/AdvancedRoute.php#L11

2. run `./artisan config:cache`

3. copy the content of the files in /tmp/controllerRoutes/, to the correct place in the route-file.

4. append urls with '/{one?}/{two?}/{three?}/{four?}/{five?}'

5. Re.order the paths so '/a/{one?}/..' comes after '/a/b/{one?}/..', or paths that start with '/a/b' will be parsend as '/a/' with parameter one = 'b'.
