### ISSUE TITLE
On addition to ReadMe needed

### ISSUE THREAD

**Issue by therlihy** [lesichkovm/laravel-advanced-route#23]
Pre-fixing the method name: You omitted this method-name convention, which must be followed (for those who don't already) or the package doesn't work (this came from another of your posts):

"Have in mind you have to follow a convention by prefixing the method names with the request method, which I personally find very clean and developer friendly:

InvoicesController@getInvoices => /invoices
InvoicesController@getInvoicesData => /invoices/data"

**Comment by Sinevia** [comment]
I am sorry @therlihy  but not sure what needs changing. May be there is something I am missing.

**Comment by therlihy** [comment]
Your software works well, but only if the methods in the Controller begin
with "get" or "post". Laravel 5 does not require this convention, and I
have not prefixed my methods with "get" or "post".

I will adopt the convention now so I can use your routing improvement.

However, the next person who tries to use may fail like I did originally,
because he does not use the prefixes.

Is this clear?

**Comment by lesichkovm** [comment]
@therlihy thank you for clarifying. I see what you mean now. 
This is not part of the README as this is how the original Laravel router for controllers worked, so it is clear for everyone who had used it.
However, I appreciate people may not have used it before, and this could be helpful for them.
If you update the README and submit it as a pull request I will be happy to review and accept it.

**Comment by therlihy** [comment]
I do not use github (although I have an account), so I cannot generate a pull request as you asked me to.

Perhaps you can modify the ReadMe to that the NEW PARAGRAPH BELOW IN ALL CAPS can be added above--
Acknowledgements

CAUTION

ALTHOUGH LARAVEL NO LONGER REQUIRES METHOD NAMES IN CONTROLLERS TO BE PREFIXED WITH "GET" OR "POST" (OR ANOTHER PREFIX), THIS PACKAGE WILL NOT WORK WITHOUT PREFIXED METHOD NAMES, SO YOU MAY NEED TO MODIFY YOURS. NOTE THAT THE EXAMPLES HERE ARE ALL PREFIXED -- [EVEN THE ONE PREFIXED WITH "MISSING ?].

**Comment by therlihy** [comment]
I have responded directly on github. I am not capable enough to generate a
pull request.

TWH

**Comment by lesichkovm** [comment]
@therlihy I do not see why we should scream at people with capital letters. A paragraph of the method naming conbention would be more helpful.

**Comment by lesichkovm** [comment]
@therlihy I have updated the README with a section "How to Use". There is an example controller which will be helpful for people who see this approach first time.

**Comment by therlihy** [comment]
I agree. I only used the ALL CAPS when I thought I could do a pull request
and embed it in the existing text. It was simply to distinguish the new
from the old.

**Comment by therlihy** [comment]
Very nice solution. Thanks for this effort and for your software.

TWH

**Comment by therlihy** [comment]
Hello and Happy New Year.

I have one more suggestion for your very useful software. I have it fully
installed and working well.

Would you consider authoring a second version that works for projects where
the functions do NOT begin with the HTTP verbs they respond to? I attempted
to revise your AdvancedController class to accomplish this, but I couldn't
figure out how it works. It does appear that a second version would be a
simplified version of the first because the leading verb would not have to
be stripped.

I looked at the Laravel "Foundation" classes in the vendor folder, and it
appears that Laravel itself is written without the leading HTTP verbs.

A second version might make your project more popular. As a late comer to
Laravel, I did not employ the verbs (for simplicity), and so I had to go
through about 200 functions to make them compliant with your software. Some
other newbies might consider that too much work.

Just a thought!

TWH

**Comment by lesichkovm** [comment]
@therlihy Happy holidays to you too.

I am not very sure what is the request. How will it work without the HTTP verbs? Probably a small example will be helpful.

**Comment by therlihy** [comment]
Sorry, I cannot offer an example, because I do not have the programming
skill necessary to understand how your class works. Instead, I'd like to
offer a clarification of my earlier suggestion.

First, from your response, it appears I may be missing some important
coding concept, so apologies in advance if so.



Second, I'd like to set forth below several observations, and then make my
case based on them.


*OBSERVATION #1*: Until I converted to using your routing improvement
class, I never used HTTP verbs and everything worked perfectly.



*OBSERVATION #2*: It appears that the Laravel framework does not employ
HTTP verbs. Here's a sample from--



vendor>laravel>framework>src>Illuminate>Foundation>Auth>AuthenticatesUsers.php:



    /**

     * Get the login username to be used by the controller.

     * @return string

     */

    public function username()

    {

        return 'email';

    }

    /**

     * Log the user out of the application.

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function logout(Request $request)

    {

        $this->guard()->logout();

        $request->session()->invalidate();

        return $this->loggedOut($request) ?: redirect('/');

    }


*OBSERVATION #3*: The concept of a RESTful application perhaps assists
programmers who are new to the concept of interacting with a database to
implement simple CRUD calls, but is has limited to no value to an
experienced programmer, especially with the advanced "active record"
capabilities of Eloquent and the QueryBuilder native to Laravel.



*OBSERVATION #4*: When the Laravel command-line artisan command (below) is
invoked, it creates a skeleton RESTful controller that does not employ HTTP
verbs:



Using this command: "php artisan make:controller TestController --resource"

produces this Controller:

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class TestController extends Controller

{

/**

* Display a listing of the resource.

*

* @return \Illuminate\Http\Response

*/

public function index()

{

//

}

/**

* Show the form for creating a new resource.

*

* @return \Illuminate\Http\Response

*/

public function create()

{

//

}

/**

* Store a newly created resource in storage.

*

* @param \Illuminate\Http\Request $request

* @return \Illuminate\Http\Response

*/

public function store(Request $request)

{

//

}

/**

* Display the specified resource.

*

* @param int $id

* @return \Illuminate\Http\Response

*/

public function show($id)

{

//

}

/**

* Show the form for editing the specified resource.

*

* @param int $id

* @return \Illuminate\Http\Response

*/

public function edit($id)

{

//

}

/**

* Update the specified resource in storage.

*

* @param \Illuminate\Http\Request $request

* @param int $id

* @return \Illuminate\Http\Response

*/

public function update(Request $request, $id)

{

//

}

/**

* Remove the specified resource from storage.

*

* @param int $id

* @return \Illuminate\Http\Response

*/

public function destroy($id)

{

//

}

}



ARGUMENT:



(1) If the observations above show that HTTP verbs are optional in a
Laravel project, it would make your AdvancedRoute class more universally
adoptable if you offered two versions -- to accommodate both the
programmers that employ HTTP verbs and those who do not.



(2) I may be wrong, but I think that newcomers opt for the RESTful resource
controller that artisan fabricates and do not employ HTTP verbs.


TWH

**Comment by lesichkovm** [comment]
@therlihy 

Thank you for clarifying. I see what you are after.

The reason HTTP verbs are used is that it makes your code very readable. You know exacly when a request is a POST or a GET.

If you do not use a POST or GET the request can be any, and it will cause confusion when you have controller with many methods. 

Also from a security point it makes it risky as any method can be called even though it may not be desired to be a publicly accessible method

```
class Example {
    function checkAndDelete(){
        if (userIsAuthorised() == false) {
             return redirectToLogin();
        }

        $this->deleteUsers(); // This is a private method and should be called only from within the controller
    }

    /**
    * Supposed to be private, but developer forgot to specify its private.
    * Now publicly accessible via /example/delete-user
    */
    function deleteUsers() {
          // deleted users
    }
}
```

The above is the reason why not using HTTP verbs can be dangerous, and will not be implemented.

However, if you want to use a method for any HTTP verb you may use ANY like this:

```
class ExampleWithAny {
     /**
      * @uri /login
      */
     function anyLogin() {
     }

    /**
      * @uri /register
      */
     function anyRegister() {
     }
}
```
