### ISSUE TITLE
Trying to install under Laravel 6 fails

### ISSUE THREAD

**Issue by dweinerATL** [lesichkovm/laravel-advanced-route#27]
When updating to Laravel 6, I get the following error message:

`- lesichkovm/laravel-advanced-route dev-master requires laravel/framework 5.* -> satisfiable by laravel/framework[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].`

I believe this is because of this in `composer.json`
```
     "require": {
        "laravel/framework": "5.*"
    }
```

**Comment by lesichkovm** [comment]
Thank you for reporting it. Requirements updated. Can you try with the latest 1.6.6 and let me know how it works for you.

**Comment by dweinerATL** [comment]
Working fine now, thank you!
