### ISSUE TITLE
Trying to install under Laravel 7 fails

### ISSUE THREAD

**Issue by eard7** [lesichkovm/laravel-advanced-route#29]
Hi!
First of all thanks for the effort bringing this package. Unfortunately it throws an error when trying to install it with the new Laravel 7. It looks like is related to the composer configuration.

Thanks!

**Comment by lesichkovm** [comment]
Thank you for letting me know @eard7. I have updated composer configuration and released new update.
Please test and let me know how it works for you.
Unfortunately I have not yet projects on Laravel 7 to test with.
