### ISSUE TITLE
Class 'AdvancedRoute' not found in new Laravel 8

### ISSUE THREAD

**Issue by Bulmer** [lesichkovm/laravel-advanced-route#30]
I get the error "Class 'AdvancedRoute' not found" when using the routes in routes/web.php, in my new Laravel 8 app. I can't see anything on the page here about any config change needed?

**Comment by Bulmer** [comment]
Actually I found that what happened was that when I installed "laravel/ui" then laravel-advanced-route was removed. Not sure why.

**Comment by lesichkovm** [comment]
@Bulmer did you sort it out?

**Comment by Bulmer** [comment]
Yes, it was some Composer problem. Working now.
