### ISSUE TITLE
laravel 11

### ISSUE THREAD

**Issue by aa-hridoy** [lesichkovm/laravel-advanced-route#34]
Problem 1
    - lesichkovm/laravel-advanced-route[1.0.0, ..., v1.6.5] require laravel/framework 5.* -> found laravel/framework[v5.0.0, ..., v5.8.38] but it conflicts with your root composer.json require (^11.0).
    - lesichkovm/laravel-advanced-route v1.6.6 requires laravel/framework 5.*|6.* -> found laravel/framework[v5.0.0, ..., v5.8.38, v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^11.0).
    - lesichkovm/laravel-advanced-route v1.7.0 requires laravel/framework 5.*|6.*|7.* -> found laravel/framework[v5.0.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but it conflicts with your root composer.json require (^11.0).
    - lesichkovm/laravel-advanced-route v1.8.0 requires laravel/framework 5.*|6.*|7.*|8.* -> found laravel/framework[v5.0.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.0).
    - lesichkovm/laravel-advanced-route v1.9.0 requires laravel/framework 5.*|6.*|7.*|8.*|9.*|10.* -> found laravel/framework[v5.0.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.10] but it conflicts with your root composer.json require (^11.0).
    - Root composer.json requires lesichkovm/laravel-advanced-route * -> satisfiable by lesichkovm/laravel-advanced-route[1.0.0, ..., v1.9.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require lesichkovm/laravel-advanced-route:*" to figure out if any version is installable, or "composer require lesichkovm/laravel-advanced-route:^2.1" if you know which you need.

**Comment by lesichkovm** [comment]
Changed composer to support v11
