### ISSUE TITLE
Method App\Http\Controllers\SettingsController::anyIndex() does not exist

### ISSUE THREAD

**Issue by Metallist1** [lesichkovm/laravel-advanced-route#4]
Firstly i would like to thank you . What you created is very usefull for me . But i got an issue .
Even though i fixed it (forgive me , im new in the programming scene an only want to help fellow companions in arms ! )
So firstly this is my code
![adad](https://cloud.githubusercontent.com/assets/25120242/21958824/8cf42d10-dabf-11e6-8422-f71f0ae59bc0.PNG)
 
Used your example . And it worked for only a limited range . But if i try to access any of the other controllers this is throw.
![dsesd](https://cloud.githubusercontent.com/assets/25120242/21958836/e8459c9e-dabf-11e6-8b54-d1fcc9026771.PNG)

(crossing out my ip for personal reasons )

And i found out that by removing this line .(highlited )
![ese](https://cloud.githubusercontent.com/assets/25120242/21958838/037e3d4a-dac0-11e6-9710-1b9419e7f4a8.PNG)
It solves this issue and fixes it completely !

All in all . Im just reporting this for other people if they got problems !
Cheers from Lithuania !

**Comment by Bulmer** [comment]
I've just started using AdvancedRoute as well. You don't have to change the
vendor source. Just change your SettingsController "getIndex" method to
"anyIndex" instead. Change any others in your project as well.

**Comment by Metallist1** [comment]
Well i did that at first. But most of my controllers dont have an "getIndex". ( only my settings controller had it , but others dont have it ) so when i tried to access other ones the same error is thrown.

Example would be my price controller , once i accessed it , the same error is throw but when i was with laravel 5.2 it worked as intended . But after my "fix" (quotes because i know its a bit noobish fix xD ) its working as it used to .


But as you mentioned , simply replacing getIndex to anyIndex should work for most people !

**Comment by lesichkovm** [comment]
I believe the latest pull request fixes this issue.
