### ISSUE TITLE
Enhacement: Add names to controllers

### ISSUE THREAD

**Issue by rigeliux** [lesichkovm/laravel-advanced-route#5]
Like old (L5.1): https://laravel.com/docs/5.1/controllers#implicit-controllers
You can put names to your controller's functions:

AdvancedRoute::controller('users', 'UserController', [
    'getShow' => 'user.show',
]);

**Comment by lesichkovm** [comment]
@rigeliux I do not use names, I find it counterproductive. Named routes are not checked if valid, and can easily reach production throwing the lovely exceptions we all know of. But if you do develop this feature, its fine with me to merge.
