### ISSUE TITLE
compatability with 5.4?

### ISSUE THREAD

**Issue by Bulmer** [lesichkovm/laravel-advanced-route#8]
Just wondering if/when this will be compatible with laravel 5.4? Im getting a dependency error with Composer update.

**Comment by lesichkovm** [comment]
@Bulmer 5.4 will be supported. This will happen once I port my first project to 5.4 :)

**Comment by Bulmer** [comment]
Thanks Milan. Just a headsup that i've been using it as an autoloaded class
on 5.4 for a few days now with no problems.

**Comment by lesichkovm** [comment]
@Bulmer 5.4 dependency fixed
